In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sumpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns


In [3]:
df=pd.read_csv('/Users/masoomsingh/Desktop/aqi_raw.csv')
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
0,2022-01-01,NaN,108.863806,56.032608,67.924893,NaN,124.154301,30.930278,13.491951,10.943885,458.517445
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
2,2022-01-03,295.477637,NaN,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930
3,2022-01-04,243.476809,NaN,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,NaN,322.416597
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,NaN,208.486255,28.189485,34.584366,7.966478,431.674874
996,2024-09-23,367.752294,479.175018,35.668276,NaN,0.684967,155.933920,31.681474,28.856730,2.897871,NaN
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,NaN,231.893166,41.463075,50.979587,14.676836,474.419799
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,NaN,91.759379,2.064906,NaN


In [4]:
df.isnull().sum()

Date             0
PM2.5          100
PM10           100
NO2            100
SO2            100
CO             100
O3             100
Temperature    100
Humidity       100
WindSpeed      100
AQI            100
dtype: int64

In [5]:
df.fillna(df.median(numeric_only=True), inplace=True)
df

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI
0,2022-01-01,203.412225,108.863806,56.032608,67.924893,2.523531,124.154301,30.930278,13.491951,10.943885,458.517445
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031
2,2022-01-03,295.477637,269.153978,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930
3,2022-01-04,243.476809,269.153978,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.470398,322.416597
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-22,45.717009,335.338475,173.732673,45.326489,2.523531,208.486255,28.189485,34.584366,7.966478,431.674874
996,2024-09-23,367.752294,479.175018,35.668276,49.432487,0.684967,155.933920,31.681474,28.856730,2.897871,259.012697
997,2024-09-24,63.359266,53.099848,65.408633,40.668087,2.523531,231.893166,41.463075,50.979587,14.676836,474.419799
998,2024-09-25,380.592568,47.386266,61.558879,53.934178,4.097152,150.734284,24.434990,91.759379,2.064906,259.012697


In [6]:
df['Date'] = pd.to_datetime(df['Date'])

In [7]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.dayofweek
df.head(5)

,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,Year,Month,Day,Weekday
0,2022-01-01,203.412225,108.863806,56.032608,67.924893,2.523531,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1,5
1,2022-01-02,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2,6
2,2022-01-03,295.477637,269.153978,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3,0
3,2022-01-04,243.476809,269.153978,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4,1
4,2022-01-05,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.470398,322.416597,2022,1,5,2


In [8]:
df.drop('Date', axis=1, inplace=True)

In [9]:
def categorize_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Satisfactory"
    elif aqi <= 200:
        return "Moderate"
    elif aqi <= 300:
        return "Poor"
    elif aqi <= 400:
        return "Very Poor"
    else:
        return "Severe"

In [11]:
df['AQI_Category'] = df['AQI'].apply(categorize_aqi)

In [12]:
df.head(5)

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,Year,Month,Day,Weekday,AQI_Category
0,203.412225,108.863806,56.032608,67.924893,2.523531,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1,5,Severe
1,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2,6,Poor
2,295.477637,269.153978,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3,0,Very Poor
3,243.476809,269.153978,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4,1,Poor
4,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.470398,322.416597,2022,1,5,2,Very Poor


In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['AQI_Category'] = le.fit_transform(df['AQI_Category'])

In [14]:
df.head(5)

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,Year,Month,Day,Weekday,AQI_Category
0,203.412225,108.863806,56.032608,67.924893,2.523531,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1,5,4
1,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2,6,2
2,295.477637,269.153978,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3,0,5
3,243.476809,269.153978,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4,1,2
4,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.470398,322.416597,2022,1,5,2,5


In [15]:
X = df.drop(['AQI', 'AQI_Category'], axis=1)
y = df['AQI_Category']

In [16]:
df.head(5)

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,WindSpeed,AQI,Year,Month,Day,Weekday,AQI_Category
0,203.412225,108.863806,56.032608,67.924893,2.523531,124.154301,30.930278,13.491951,10.943885,458.517445,2022,1,1,5,4
1,380.778579,280.112455,53.160866,80.074777,4.046618,147.296341,11.895454,26.809528,10.465604,272.173031,2022,1,2,6,2
2,295.477637,269.153978,181.719643,26.545854,3.824789,257.818744,39.895783,84.812122,1.888436,367.956930,2022,1,3,0,5
3,243.476809,269.153978,53.661509,63.237662,0.854110,108.601272,29.524650,79.009152,13.877300,229.303183,2022,1,4,1,2
4,70.847270,407.149351,58.030197,58.031106,0.831322,262.198409,11.288155,41.557842,7.470398,322.416597,2022,1,5,2,5


In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [21]:
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
print(X_scaled_df)

        PM2.5      PM10       NO2       SO2        CO        O3  Temperature  \
0    0.028692 -1.175412 -0.863624  0.675841  0.000294 -0.396249     0.557061   
1    1.683196  0.119395 -0.916889  1.134479  1.140278 -0.104042    -1.175511   
2    0.887494  0.036538  1.467593 -0.886148  0.974245  1.291492     1.373112   
3    0.402421  0.036538 -0.907603  0.498906 -1.249217 -0.592633     0.429119   
4   -1.207897  1.079919 -0.826573  0.302367 -1.266272  1.346792    -1.230788   
..        ...       ...       ...       ...       ...       ...          ...   
995 -1.442316  0.536958  1.319452 -0.177211  0.000294  0.668585     0.307591   
996  1.561684  1.624504 -1.241338 -0.022216 -1.375815  0.005023     0.625436   
997 -1.277746 -1.597043 -0.689720 -0.353058  0.000294  0.964137     1.515769   
998  1.681461 -1.640243 -0.761124  0.147715  1.178101 -0.060632    -0.034148   
999 -0.152927 -0.823177  1.341581 -1.215761  0.376998 -1.290644     0.459670   

     Humidity  WindSpeed      Year     

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [19]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [21]:
from sklearn.svm import SVC

svm = SVC(probability=True)
svm.fit(X_train, y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",True
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [22]:
y_pred_lr = lr.predict(X_test)
y_pred_knn = knn.predict(X_test)
y_pred_svm = svm.predict(X_test)

In [23]:
from sklearn.metrics import classification_report

print("Logistic Regression:\n", classification_report(y_test, y_pred_lr))
print("KNN:\n", classification_report(y_test, y_pred_knn))
print("SVM:\n", classification_report(y_test, y_pred_svm))

Logistic Regression:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.10      0.03      0.04        40
           2       0.30      0.82      0.44        62
           3       0.00      0.00      0.00        13
           4       0.15      0.06      0.09        34
           5       0.00      0.00      0.00        38

    accuracy                           0.27       200
   macro avg       0.09      0.15      0.09       200
weighted avg       0.14      0.27      0.16       200

KNN:
               precision    recall  f1-score   support

           0       0.18      0.15      0.17        13
           1       0.18      0.23      0.20        40
           2       0.33      0.47      0.39        62
           3       0.00      0.00      0.00        13
           4       0.25      0.18      0.21        34
           5       0.10      0.05      0.07        38

    accuracy                           0.24      

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this beha

In [24]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred_lr))

[[ 0  1 11  0  1  0]
 [ 0  1 35  0  2  2]
 [ 0  3 51  0  5  3]
 [ 0  0 11  0  2  0]
 [ 0  4 24  0  2  4]
 [ 0  1 36  0  1  0]]


In [25]:
from sklearn.metrics import accuracy_score

print("LR Accuracy:", accuracy_score(y_test, y_pred_lr))
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))

LR Accuracy: 0.27
KNN Accuracy: 0.24
SVM Accuracy: 0.3


In [26]:
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_auc_score

y_test_bin = label_binarize(y_test, classes=[0,1,2,3,4,5])

y_prob = svm.predict_proba(X_test)

roc_score = roc_auc_score(y_test_bin, y_prob, multi_class='ovr')
print("ROC AUC Score:", roc_score)

ROC AUC Score: 0.5280658452708966
